/** Exact deterministic Ace recipient ingress. Reserved requests never reach a model. */
import type { WebClient } from '@slack/web-api';
import { Client as NotionClient } from '@notionhq/client';
import { receiveAceHandoff, OFFICE_ID, type Config, type Store, type Provider, type SendReceipt } from './ace-handoff-core.js';
import { getSupabase } from '../integrations/supabase.js';
import { env } from '../env.js';
import { updateAotTaskStatus } from '../agents/tools/aot-notion-tools.js';
import { logWrite } from '../agents/action-log.js';
import { createProductionAdaPerformanceProvider } from './ace-ada-performance.js';
import { logger } from '../utils/logger.js';
export const isAceHandoffCommand=(text:string)=>/^\s*ace_handoff(?:\s|$)/i.test(text);
interface Options {client:WebClient;agentId:string;text:string;userId:string;channel:string;messageTs:string;threadTs?:string;source?:string}
export interface BridgeDependencies {config?:Config|null;store?:Store;provider?:Provider;now?:()=>Date}
export function createAceHandoffStore():Store {
 const db=getSupabase(),namespace='ace_meeting_v1';
 return {get:async<T>(key:string)=>{const {data,error}=await db.from('ace_workflow_records').select('revision,value').eq('namespace',namespace).eq('record_key',key).abortSignal(AbortSignal.timeout(15000)).maybeSingle();if(error)throw new Error('Handoff durable read failed');if(!data)return null;const revision=Number(data.revision);if(!Number.isSafeInteger(revision)||revision<1)throw new Error('Invalid handoff revision');return {revision,value:data.value as T};},cas:async(key,revision,value)=>{const {data,error}=await db.rpc('ace_workflow_compare_and_set',{p_namespace:namespace,p_record_key:key,p_expected_revision:revision,p_value:value}).abortSignal(AbortSignal.timeout(15000));if(error||typeof data!=='boolean')throw new Error('Handoff durable CAS failed');return data;}};
}
export function createAceHandoffProvider(options:Options,config:Config,now:()=>Date=()=>new Date(),fetcher:typeof fetch=fetch):Provider {
 const stop=Math.min(Date.parse(config.pilot.expiresAt),now().getTime()+60000);
 const active=()=>{if(now().getTime()>=stop)throw new Error('Recipient provider deadline expired');};
 async function raw(path:string,body?:unknown){active();if(!env.NOTION_TOKEN)throw new Error('Existing Notion integration is unavailable');const response=await fetcher(`https://api.notion.com/v1/${path}`,{method:body===undefined?'GET':'POST',headers:{Authorization:`Bearer ${env.NOTION_TOKEN}`,'Notion-Version':'2025-09-03','Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),redirect:'error',signal:AbortSignal.timeout(Math.max(1,Math.min(15000,stop-now().getTime())))});if(!response.ok||!response.body)throw new Error('Notion source read failed');const reader=response.body.getReader();const chunks:Uint8Array[]=[];let bytes=0;try{for(;;){const chunk=await reader.read();if(chunk.done)break;bytes+=chunk.value.length;if(bytes>500000)throw new Error('Notion source exceeds read bound');chunks.push(chunk.value);}}finally{await reader.cancel().catch(()=>undefined);}active();return JSON.parse(Buffer.concat(chunks).toString('utf8'));}
 const page=async(id:string)=>{const p=await raw(`pages/${id}`);if(p.object!=='page'||p.id!==id||p.archived||p.in_trash)throw new Error('Exact active Notion source missing');return p;};
 const prop=(p:any,name:string)=>{const all=Object.values(p.properties??{}) as any[],found=p.properties?.[name]??all.find(v=>v.id===name);if(!found)throw new Error('Exact source property missing');return found;};
 const relation=(p:any,name:string):string[]=>{const v=prop(p,name);if(v.type!=='relation'||v.has_more===true||!Array.isArray(v.relation))throw new Error('Incomplete exact relation');return v.relation.map((r:any)=>r.id);};
 const completeRelation=async(p:any,name:string):Promise<string[]>=>{const v=prop(p,name);if(v.has_more!==true)return relation(p,name);if(v.type!=='relation'||typeof v.id!=='string')throw new Error('Incomplete relation');let cursor:string|undefined;const ids:string[]=[],seen=new Set<string>();for(let i=0;i<5;i++){const response=await raw(`pages/${p.id}/properties/${encodeURIComponent(decodeURIComponent(v.id))}?page_size=100${cursor?`&start_cursor=${encodeURIComponent(cursor)}`:''}`);if(!Array.isArray(response.results))throw new Error('Relation result missing');for(const child of response.results){if(child.type!=='relation'||typeof child.relation?.id!=='string'||seen.has(child.relation.id))throw new Error('Relation scope malformed');seen.add(child.relation.id);ids.push(child.relation.id);}if(ids.length>100)throw new Error('Relation exceeds 100-record bound');if(response.has_more===false&&response.next_cursor===null)return ids;if(response.has_more!==true||typeof response.next_cursor!=='string'||!response.next_cursor||response.next_cursor===cursor)throw new Error('Relation pagination incomplete');cursor=response.next_cursor;}throw new Error('Relation exceeds five-page bound');};
 const status=(p:any,name:string)=>{const v=prop(p,name);if(!['status','select'].includes(v.type)||!v[v.type]?.name)throw new Error('Exact status missing');return v[v.type].name as string;};
 const title=(p:any,name:string)=>{const v=prop(p,name);if(v.type!=='title')throw new Error('Exact task title missing');return v.title.map((r:any)=>r.plain_text??r.text?.content??'').join('');};
 const exact=(a:string[],b:string[])=>JSON.stringify([...a].sort())===JSON.stringify([...b].sort());
 const auth=()=>options.client.auth.test();
 const readbackNotion=new NotionClient({auth:env.NOTION_TOKEN,timeoutMs:15000,fetch:async(...args)=>{active();const response=await fetcher(...args);active();return response;}});
 const performance=config.performanceClients?.length?createProductionAdaPerformanceProvider(config.performanceClients,now):undefined;
 return {
  ...(performance?{performance:(portalId:string,query:Parameters<typeof performance.read>[1],guard:()=>Promise<void>,requestedAt:string)=>performance.read(portalId,query,guard,requestedAt)}:{}),
  identity:async()=>{active();const a=await auth();active();return {workspaceId:a.team_id??'',userId:a.user_id??''};},
  internalOffice:async()=>{active();const r=await options.client.conversations.info({channel:OFFICE_ID});active();const c=r.channel;return r.ok===true&&c?.id===OFFICE_ID&&c.is_shared===false&&c.is_ext_shared===false&&c.is_im===false&&c.is_mpim===false&&c.is_pending_ext_shared!==true&&!(c.pending_shared?.length);},
  scope:async(t,client)=>{active();const adset=await page(t.adSetId);if(!exact(relation(adset,'Client'),[t.clientPortalId])||!exact(relation(adset,'EXT | Client Briefs'),t.source.receipts.map(r=>r.briefId)))throw new Error('Exact Ad Set/client/brief relation changed');
   const tasks:any[]=[];let cursor:string|undefined;const seen=new Set<string>();for(let i=0;i<5;i++){const q=await raw('data_sources/27e1398c-921f-81ea-ac35-000b12653a74/query',{filter:{property:'Ad Set',relation:{contains:t.adSetId}},page_size:100,...(cursor?{start_cursor:cursor}:{})});if(!Array.isArray(q.results))throw new Error('Complete task source missing');for(const p of q.results){if(typeof p.id!=='string'||seen.has(p.id))throw new Error('Duplicate task source');seen.add(p.id);tasks.push(p);}if(tasks.length>100)throw new Error('Task scope exceeds 100-record bound');if(q.has_more===false&&q.next_cursor===null)break;if(q.has_more!==true||typeof q.next_cursor!=='string'||q.next_cursor===cursor||i===4)throw new Error('Task scope exceeds complete five-page bound');cursor=q.next_cursor;}
   if(!exact(tasks.map((p:any)=>p.id),await completeRelation(adset,'Tasks')))throw new Error('Exact companion task set changed');
   for(const p of tasks){if(p.object!=='page'||p.archived||p.in_trash||!exact(relation(p,'Client'),[t.clientPortalId])||!exact(relation(p,'Ad Set'),[t.adSetId]))throw new Error('Task escaped client/adset');}
   const send=tasks.find((p:any)=>p.id===t.transitions[0]!.taskId),approval=tasks.find((p:any)=>p.id===t.transitions[1]!.taskId),signoffs=tasks.filter((p:any)=>['Sign-off Brief Internally','Sign-off brief internally'].includes(title(p,'Task name ')));
   if(!send||!approval||!['Send Brief to Client','Send brief to client'].includes(title(send,'Task name '))||!['Approve Brief','Approve brief'].includes(title(approval,'Task name '))||signoffs.length!==1||status(signoffs[0],'vdOD')!=='Done')throw new Error('Task kinds or internal signoff changed');
   for(const p of [send,approval]){const assignee=prop(p,'Assignee');if(assignee.type!=='people'||!assignee.people.some((v:any)=>v.id===client.ownerNotionId))throw new Error('Exact task owner changed');}
   const clients=await raw('data_sources/2681398c-921f-813a-9098-000b36e3e33e/query',{filter:{property:'Client Portal',relation:{contains:t.clientPortalId}},page_size:2});if(clients.has_more!==false||clients.next_cursor!==null||clients.results?.length!==1)throw new Error('Client policy scope incomplete');const c=clients.results[0],approvals=prop(c,'Upload Approvals');if(!exact(relation(c,'Client Portal'),[t.clientPortalId])||status(c,'Status')!=='Active'||approvals.type!=='multi_select'||!approvals.multi_select.some((v:any)=>v.name==='Brief Approval Required'))throw new Error('Client active/approval policy changed');
   for(const source of t.source.receipts){const brief=await page(source.briefId);if(!exact(relation(brief,'Ad Sets'),[t.adSetId])||(relation(brief,'Clients ').length>0&&!exact(relation(brief,'Clients '),[t.clientPortalId])))throw new Error('Brief escaped exact source scope');}
   active();return {statuses:{[send.id]:status(send,'vdOD'),[approval.id]:status(approval,'vdOD')},versions:{[send.id]:send.last_edited_time,[approval.id]:approval.last_edited_time}};},
  observedSend:async(s:SendReceipt)=>{active();if(!s.messageTs)return false;let cursor:string|undefined,match:any,seen=new Set<string>();for(let i=0;i<3;i++){const r=await options.client.conversations.replies({channel:s.channelId,ts:s.threadTs??s.messageTs,limit:100,cursor});active();if(!r.ok||!r.messages)throw new Error('Incomplete observed send');for(const m of r.messages)if(m.ts===s.messageTs){if(match)throw new Error('Duplicate observed send');match=m;}const next=r.response_metadata?.next_cursor;if(!next){if(r.has_more)throw new Error('Incomplete observed send cursor');break;}if(seen.has(next)||i===2)throw new Error('Observed send exceeds bound');seen.add(next);cursor=next;}
   if(!match||match.user!==s.actorId||match.bot_id||match.subtype==='bot_message'||String(match.edited?.ts??match.ts)!==String(s.versionTs??s.messageTs))return false;
   const compact=s.briefId.replace(/-/g,'').toLowerCase(),links=String(match.text??'').match(/https:\/\/[^\s<>|)]+/g)??[];return links.some(link=>{try{const url=new URL(link);if(url.protocol!=='https:'||url.username||url.password||!['notion.so','www.notion.so','app.notion.com','notion.com','www.notion.com'].includes(url.hostname))return false;const found=url.pathname.match(/(?:^|[-/])([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:\/|$)/i);return found?.[1]?.replace(/-/g,'').toLowerCase()===compact;}catch{return false;}});},
  write:async(taskId,expected,desired,guard)=>{active();const result=await updateAotTaskStatus({task_id:taskId,new_status:desired},{expectedStatus:expected,beforeWrite:async()=>{await guard();active();},notion:readbackNotion,propertyId:'vdOD'});active();if(result.ok&&result.before!==result.after)logWrite({context:{agentId:'piper',userId:options.userId,channelId:options.channel,threadTs:options.threadTs??options.messageTs},toolName:'update_aot_task_status',targetSystem:'notion',targetId:taskId,before:{Status:result.before},after:{Status:result.after},reverse:result.reverse,summary:`Ace confirmed handoff: ${taskId} ${result.before} → ${result.after}`});if(!result.ok||result.verified!==true||result.task_id?.replace(/-/g,'').toLowerCase()!==taskId.replace(/-/g,'').toLowerCase()||result.after!==desired)throw new Error('Piper writer outcome requires independent reconciliation');},
 };
}
export async function tryAceHandoffCommand(options:Options,deps:BridgeDependencies={}):Promise<boolean>{
 if(!isAceHandoffCommand(options.text))return false;
 const match=options.text.trim().match(/^ace_handoff v1 ([A-Za-z0-9:_-]{1,150})$/),now=deps.now??(()=>new Date());
 if(!match||options.source!=='agent-mention')return true;
 let config:Config|null;
 try{config=deps.config===undefined?process.env.ACE_HANDOFF_RECIPIENT_CONFIG?JSON.parse(process.env.ACE_HANDOFF_RECIPIENT_CONFIG):null:deps.config;}catch{return true;}
 if(!config)return true;
 try{const provider=deps.provider??createAceHandoffProvider(options,config,now),identity=await provider.identity();await receiveAceHandoff({agentId:options.agentId,userId:options.userId,workspaceId:identity.workspaceId,channelId:options.channel,messageTs:options.messageTs,threadTs:options.threadTs,requestId:match[1]!},config,deps.store??createAceHandoffStore(),provider,now);}catch{logger.warn({agentId:options.agentId},'Reserved Ace handoff rejected or requires durable reconciliation; no model fallback');}
 return true;
}
