import {describe,it,expect,vi} from 'vitest';
import {createAdaPerformanceProvider,VERIFIED_PERFORMANCE_CLIENTS} from '../src/slack/ace-ada-performance.js';
import {readFileSync} from 'node:fs';
import {receiveAceHandoff,digest,rawHash,ACE_ID,OFFICE_ID,type Store,type Config,type Provider,type Event,type Transition,type Result} from '../src/slack/ace-handoff-core.js';
class Memory implements Store {rows=new Map<string,{revision:number;value:any}>();async get<T>(key:string){return structuredClone(this.rows.get(key)??null) as {revision:number;value:T}|null;}async cas(key:string,revision:number|null,value:unknown){const current=this.rows.get(key);if((current?.revision??null)!==revision)return false;this.rows.set(key,{revision:(current?.revision??0)+1,value:structuredClone(value)});return true;}set(key:string,value:unknown){this.rows.set(key,{revision:1,value:structuredClone(value)});}}
const uid=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function fixture(){
 let clock=new Date('2026-10-03T19:00:00Z');const store=new Memory(),requestId='brief-transition-fixture',portal=uid(1),adset=uid(2),send=uid(3),approval=uid(4),brief=uid(5),draft=uid(6),actionId=uid(7),owner='UOWNER';
 const pilot={id:'test',workspaceId:'T084ZNV068Y',channelId:'CTEST',actorIds:[owner],startsAt:'2026-10-03T18:00:00Z',expiresAt:'2026-10-04T19:00:00Z',maxCases:20,maxModelJobs:40,clients:[{portalId:portal,name:'TL',participantEmails:['a@example.test']}],meetings:[]};
 const config:Config={recipientReleaseId:'f'.repeat(40),pilot,clients:[{portalId:portal,channelId:'CCLIENT',ownerNotionId:uid(8)}]};
 const source={draftId:draft,briefId:brief,receiptKey:`brief-sent:${draft}:${brief}`,sentAt:'2026-10-03T18:59:00Z',permalink:'https://slack.test/message',evidenceKind:'slack-observed'};
 const transition:Transition={requestId,workspaceId:pilot.workspaceId,sourceAgent:'ace',targetAgent:'piper',clientPortalId:portal,adSetId:adset,source:{...source,receipts:[{briefId:brief,receiptKey:source.receiptKey,sentAt:source.sentAt,permalink:source.permalink,evidenceKind:source.evidenceKind}]},transitions:[{taskId:send,propertyId:'vdOD',expectedStatus:'In Progress',desiredStatus:'Done'},{taskId:approval,propertyId:'vdOD',expectedStatus:'Blocked',desiredStatus:'In Progress'}]};
 const request={requestId,workspaceId:pilot.workspaceId,sourceAgent:'ace',targetAgent:'piper',clientPortalId:portal,channelId:OFFICE_ID,originalThread:{channelId:'CTEST',threadTs:'1791053999.001'},createdAt:'2026-10-03T18:59:01Z',expiresAt:'2026-10-03T19:29:00Z',maxPolls:10,payload:{kind:'piper-brief-transitions',transition}};
 const action={id:actionId,createdAt:request.createdAt,scope:{workspaceId:pilot.workspaceId,channelId:'CTEST',threadTs:request.originalThread.threadTs,actorId:owner,clientId:portal},kind:'brief-operation',payload:{name:'ace_brief_request_status',input:{draftId:draft,briefIds:[brief]}},expiresAt:request.expiresAt,state:'executing'};
 store.set(`pilot:${pilot.id}`,{configHash:rawHash(JSON.stringify(pilot)),cases:[`handoff:${requestId}`],jobs:[]});store.set(`agent-handoff:${rawHash(requestId)}`,{request,requestHash:digest(request)});store.set(`agent-handoff-authorization:${requestId}`,{version:1,actionId,requestHash:digest(request),expiresAt:request.expiresAt});store.set(`workspace-action:${actionId}`,action);
 store.set(`brief-draft:${draft}`,{id:draft,clientPortalId:portal,channelId:'CCLIENT',items:[{adSet:{id:adset},sendTask:{id:send},approvalTask:{id:approval},briefs:[{id:brief}]}]});store.set(source.receiptKey,{key:source.receiptKey,draftId:draft,briefId:brief,adSetId:adset,clientPortalId:portal,sendTaskId:send,approvalTaskId:approval,actorId:owner,channelId:'CCLIENT',active:true,kind:source.evidenceKind,sentAt:source.sentAt,permalink:source.permalink,messageTs:'1791053940.001'});
 const statuses:Record<string,string>={[send]:'In Progress',[approval]:'Blocked'},versions:Record<string,string>={[send]:'v1',[approval]:'v1'};let writes:string[]=[],lost=false,fail=false;
 const provider:Provider={identity:async()=>({workspaceId:pilot.workspaceId,userId:'U0B7AF0N3CL'}),internalOffice:async()=>true,scope:async()=>({statuses:{...statuses},versions:{...versions}}),observedSend:async()=>true,write:async(id,expected,desired,guard)=>{await guard();writes.push(id);if(fail)throw Error('lost before write');expect(statuses[id]).toBe(expected);statuses[id]=desired;versions[id]='v2';if(lost)throw Error('lost response');}};
 const event:Event={agentId:'piper',userId:ACE_ID,workspaceId:pilot.workspaceId,channelId:OFFICE_ID,messageTs:'1791054000.001',requestId};
 return {store,config,provider,event,transition,request,action,statuses,versions,writes,send,approval,source,now:()=>clock,setClock:(v:string)=>clock=new Date(v),lose:()=>lost=true,fail:()=>fail=true,run:()=>receiveAceHandoff(event,config,store,provider,()=>clock)};
}
describe('Exact deterministic Ace recipient',()=>{
 it('writes precisely one pair, independently rereads, survives restart/replay without another write',async()=>{const f=fixture(),r=await f.run();expect(r.state).toBe('verified');expect(r.recipientReleaseId).toBe('f'.repeat(40));expect(f.writes).toEqual([f.send,f.approval]);expect(await f.run()).toEqual(r);expect(f.writes).toHaveLength(2);});
 it.each(['userId','channelId','workspaceId'])('refuses forged %s before writes',async field=>{const f=fixture();(f.event as any)[field]='FORGED';await expect(f.run()).rejects.toThrow();expect(f.writes).toEqual([]);});
 it('requires exact recipient identity and nonshared office',async()=>{const f=fixture();f.provider.identity=async()=>({workspaceId:f.config.pilot.workspaceId,userId:ACE_ID});await expect(f.run()).rejects.toThrow();f.provider.identity=async()=>({workspaceId:f.config.pilot.workspaceId,userId:'U0B7AF0N3CL'});f.provider.internalOffice=async()=>false;await expect(f.run()).rejects.toThrow();expect(f.writes).toEqual([]);});
 it('refuses expiry, expanded pilot config and proposed/unconfirmed action',async()=>{const f=fixture();f.setClock('2026-10-03T19:29:00Z');await expect(f.run()).rejects.toThrow();const g=fixture();g.config.pilot.maxCases=19;await expect(g.run()).rejects.toThrow();const h=fixture();h.store.set(`workspace-action:${h.action.id}`,{...h.action,state:'proposed'});await expect(h.run()).rejects.toThrow();});
 it('reconciles a lost committed response without repeating or inventing completion',async()=>{const f=fixture();f.lose();expect((await f.run()).state).toBe('verified');expect(f.writes).toHaveLength(2);await f.run();expect(f.writes).toHaveLength(2);});
 it('does not unblock approval after an uncertain first write',async()=>{const f=fixture();f.fail();expect((await f.run()).state).toBe('unknown');expect(f.writes).toEqual([f.send]);expect((await f.run()).state).toBe('unknown');expect(f.writes).toHaveLength(1);});
 it('resumes after process crash with first prepared write independently found Done, writes only second',async()=>{const f=fixture();f.statuses[f.send]='Done';f.store.set(`agent-recipient:${rawHash(f.event.requestId)}`,{version:1,requestId:f.event.requestId,requestHash:digest(f.request),authorizationHash:digest(f.store.rows.get(`agent-handoff-authorization:${f.event.requestId}`)!.value),workspaceId:f.event.workspaceId,recipientUserId:'U0B7AF0N3CL',recipientReleaseId:f.config.recipientReleaseId,clientPortalId:f.request.clientPortalId,state:'unknown',items:[{...f.transition.transitions[0],state:'prepared',before:'In Progress'}]});expect((await f.run()).state).toBe('verified');expect(f.writes).toEqual([f.approval]);});
 it('retains partial receipts if source disappears before second write, never repeats first',async()=>{const f=fixture(),original=f.provider.scope;let reads=0;f.provider.scope=async(...args)=>{reads++;if(reads===4)throw Error('source unavailable');return original(...args);};const r=await f.run();expect(r.state).toBe('partial');expect(r.items[0]?.state).toBe('verified');expect(f.writes).toEqual([f.send]);f.provider.scope=original;expect((await f.run()).state).toBe('verified');expect(f.writes).toEqual([f.send,f.approval]);});
 it('holds changed sources and wrong-client receipts',async()=>{const f=fixture();f.provider.observedSend=async()=>false;expect((await f.run()).state).toBe('rejected');expect(f.writes).toEqual([]);const g=fixture();g.store.rows.get(g.source.receiptKey)!.value.clientPortalId=uid(99);expect((await g.run()).state).toBe('rejected');expect(g.writes).toEqual([]);});
 it('fences a receipt edited while guard is awaiting the provider',async()=>{const f=fixture(),original=f.provider.scope;let reads=0;f.provider.scope=async(...args)=>{if(++reads===1){const row=f.store.rows.get(f.source.receiptKey)!;row.revision++;row.value.active=false;}return original(...args);};expect((await f.run()).state).toBe('unknown');expect(f.writes).toEqual([]);});
 it('permits JSONB key reordering and executing→verified confirmation while keeping immutable scope',async()=>{const f=fixture(),original=f.provider.scope;f.provider.scope=async(...args)=>{const row=f.store.rows.get(`workspace-action:${f.action.id}`)!;row.value={...row.value,state:'verified',result:{queued:true}};return original(...args);};const requestRow=f.store.rows.get(`agent-handoff:${rawHash(f.event.requestId)}`)!;requestRow.value.request=Object.fromEntries(Object.entries(requestRow.value.request).reverse());expect((await f.run()).state).toBe('verified');});
 it('rejects malformed or unsupported typed operations, never dispatches a generic agent',async()=>{const f=fixture();f.request.payload.kind='generic-agent';f.store.set(`agent-handoff:${rawHash(f.event.requestId)}`,{request:f.request,requestHash:digest(f.request)});const proof=f.store.rows.get(`agent-handoff-authorization:${f.event.requestId}`)!.value;proof.requestHash=digest(f.request);expect((await f.run()).state).toBe('rejected');expect(f.writes).toEqual([]);});
 it('rejects unknown release/hash result rather than reuse another receipt',async()=>{const f=fixture();f.store.set(`agent-recipient:${rawHash(f.event.requestId)}`,{requestHash:'bad',authorizationHash:'bad'});await expect(f.run()).rejects.toThrow('Conflicting');expect(f.writes).toEqual([]);});
 it('has a deterministic reserved interceptor before both legacy Piper and model routing',()=>{const source=readFileSync(new URL('../src/slack/dedicated-bots.ts',import.meta.url),'utf8');expect(source.indexOf('if (await tryAceHandoffCommand(opts)) return;')).toBeLessThan(source.indexOf("if (agentId === 'piper' && await tryPiperPilotCommand(opts))"));const bridge=readFileSync(new URL('../src/slack/ace-handoff-bridge.ts',import.meta.url),'utf8');expect(bridge).not.toContain('runAgent');});
});

describe('Last admission boundary',()=>{
 it('never writes approval if the previously verified send drifts before its guard',async()=>{const f=fixture(),original=f.provider.scope;let reads=0;f.provider.scope=async(...args)=>{if(++reads===5){f.statuses[f.send]='In Progress';f.versions[f.send]='human-revert';}return original(...args);};const result=await f.run();expect(result.state).toBe('unknown');expect(f.writes).toEqual([f.send]);expect(result.items[0]?.state).toBe('conflict');expect(result.items[1]?.state).toBe('unknown');});
 it('holds if original draft changes during reads',async()=>{const f=fixture(),original=f.provider.scope;f.provider.scope=async(...args)=>{f.store.rows.get(`brief-draft:${f.source.draftId}`)!.value.items[0].briefs.push({id:uid(55)});return original(...args);};expect((await f.run()).state).toBe('unknown');expect(f.writes).toEqual([]);});
 it('requires the exact sender-reserved pilot case',async()=>{const f=fixture();f.store.rows.get(`pilot:${f.config.pilot.id}`)!.value.cases=['unrelated'];await expect(f.run()).rejects.toThrow('reserved');expect(f.writes).toEqual([]);});
 it('checks expiry after an awaited source returns',async()=>{const f=fixture(),original=f.provider.scope;f.provider.scope=async(...args)=>{const value=await original(...args);f.setClock('2026-10-03T19:29:00Z');return value;};expect((await f.run()).state).toBe('rejected');expect(f.writes).toEqual([]);});
});

function adaFixture(){const f=fixture(),pin={...VERIFIED_PERFORMANCE_CLIENTS[0]!},query={days:7 as const,startDate:'2026-09-26',endDate:'2026-10-02'};f.config.performanceClients=[pin];f.config.pilot.clients[0]!.portalId=pin.portalId;f.event.agentId='ada';const request={...f.request,targetAgent:'ada' as const,clientPortalId:pin.portalId,payload:{kind:'ada-account-performance',performance:query}};const action={...f.action,scope:{...f.action.scope,clientId:pin.portalId},kind:'performance-read',payload:{name:'ace_request_performance',query}};f.store.set(`pilot:${f.config.pilot.id}`,{configHash:rawHash(JSON.stringify(f.config.pilot)),cases:[`handoff:${request.requestId}`],jobs:[]});f.store.set(`agent-handoff:${rawHash(request.requestId)}`,{request,requestHash:digest(request)});f.store.set(`agent-handoff-authorization:${request.requestId}`,{version:1,actionId:action.id,requestHash:digest(request),expiresAt:request.expiresAt});f.store.set(`workspace-action:${action.id}`,action);f.provider.identity=async()=>({workspaceId:f.config.pilot.workspaceId,userId:'U0AHK9K5GEB'});const source={client:vi.fn(async()=>({data:[{id:pin.sourceClientId,code:pin.sourceCode,ad_account_id:pin.adAccountId,data_source:pin.dataSource,timezone:pin.timezone,currency:pin.currency,is_active:true}]})),rows:vi.fn(async()=>({data:[],count:0}))};const reader=createAdaPerformanceProvider(source,[pin],f.now);f.provider.performance=reader.read;return {...f,query,request,action,source};}
describe('Ada confirmed stored-performance intake',()=>{
 it('returns bounded partial artifact only and preserves exact dates on restart',async()=>{const f=adaFixture(),result=await f.run();expect(result.state).toBe('partial');expect(result.performance?.freshness.state).toBe('unverified');expect(result.performance?.window).toMatchObject({...f.query,requestedAt:f.request.createdAt});expect(f.writes).toEqual([]);expect(f.source.rows).toHaveBeenCalledOnce();const revision=f.store.rows.get(`agent-recipient:${rawHash(f.event.requestId)}`)!.revision;const replay=await f.run();expect(f.store.rows.get(`agent-recipient:${rawHash(f.event.requestId)}`)!.revision).toBe(revision);expect(replay).toEqual(result);expect(replay.performance).toEqual(result.performance);expect(f.source.rows).toHaveBeenCalledOnce();expect(f.writes).toEqual([]);});
 it('rejects model-selected query lacking exact human action authority',async()=>{const f=adaFixture();f.store.rows.get(`workspace-action:${f.action.id}`)!.value.payload.query.days=14;expect((await f.run()).state).toBe('rejected');expect(f.source.rows).not.toHaveBeenCalled();expect(f.writes).toEqual([]);});
 it('holds action/source mutation during bounded reader without publishing an artifact',async()=>{const f=adaFixture();f.source.rows.mockImplementation(async()=>{f.store.rows.get(`workspace-action:${f.action.id}`)!.value.scope.actorId='UFORGED';return {data:[],count:0};});const result=await f.run();expect(result.state).toBe('rejected');expect(result.performance).toBeUndefined();expect(f.writes).toEqual([]);});
});

it('refuses an Ada date anchor different from the original confirmed proposal',async()=>{const f=adaFixture();f.store.rows.get(`workspace-action:${f.action.id}`)!.value.createdAt='2026-10-03T00:00:00Z';expect((await f.run()).state).toBe('rejected');expect(f.source.rows).not.toHaveBeenCalled();});
