export const toolProfiles = {
  readonly: ['Read', 'Glob', 'Grep', 'WebSearch', 'WebFetch'],
  standard: ['Read', 'Glob', 'Grep', 'WebSearch', 'WebFetch', 'Bash', 'ask_agent'],
  coding: ['Read', 'Glob', 'Grep', 'WebSearch', 'WebFetch', 'Bash', 'Write', 'Edit'],
  full: ['Read', 'Glob', 'Grep', 'WebSearch', 'WebFetch', 'Bash', 'Write', 'Edit', 'NotebookEdit'],
  assistant: ['recall', 'remember', 'search_memories', 'ask_agent', 'post_message', 'reply_in_thread', 'send_as_daniel', 'read_dms', 'find_user', 'get_unread_dms', 'search_meetings', 'get_meeting_summary', 'get_meeting_transcript', 'list_recent_meetings', 'query_tasks', 'create_task', 'update_task', 'add_task_comment', 'search_notion', 'get_channel_insights', 'get_recent_mentions', 'get_monitoring_history', 'generate_briefing', 'list_events', 'search_events', 'create_event', 'update_event', 'delete_event', 'check_availability', 'search_emails', 'read_email', 'draft_email', 'send_email', 'review_my_learnings', 'correct_learning', 'delete_learning', 'browse_navigate', 'browse_click', 'browse_type', 'browse_read_page', 'browse_screenshot', 'browse_select', 'browse_close'],
  media_buyer: [
    'recall', 'remember', 'search_memories',
    'list_clients', 'get_client_targets', 'get_client_performance',
    'get_campaign_summary', 'get_campaign_performance',
    'get_adset_summary', 'get_adset_performance',
    'get_ad_summary', 'get_ad_performance', 'get_breakdowns',
    'get_account_changes', 'get_creative_details',
    'get_alerts', 'get_learnings', 'get_briefs', 'get_concepts',
    'get_domo_funnel', 'get_weather_daily',
    'query_meta_insights', 'query_meta_creatives',
    'search_meetings', 'get_meeting_summary', 'get_meeting_transcript', 'list_recent_meetings',
    'post_message', 'reply_in_thread',
    'log_decision',
    'search_methodology',
    'correct_learning', 'delete_learning',
    'correct_methodology', 'delete_methodology',
    'query_tasks', 'create_task', 'update_task', 'add_task_comment', 'search_notion',
    'query_aot_tasks', 'query_aot_adsets', 'count_aot_tasks', 'count_aot_adsets',
    'generate_weekly_report',
    'scan_media_library_folder', 'upload_to_media_library',
    'get_client_capabilities', 'preview_ad_launch', 'launch_ads',
    'pause_launch', 'update_landing_page_mapping',
    'qc_copy', 'verify_launch', 'poll_analysis', 'set_adset_marker',
  ],
  creative_strategist: [
    'recall', 'remember', 'search_memories',
    'ask_ada',
    'get_creative_audit', 'get_creative_diversity_score',
    'search_methodology',
    'post_message', 'reply_in_thread',
    'search_meetings', 'get_meeting_summary', 'get_meeting_transcript', 'list_recent_meetings',
    'query_tasks', 'create_task', 'update_task', 'add_task_comment', 'search_notion',
  ],
  client_media_buyer: [
    'recall', 'remember', 'search_memories',
    'get_client_targets', 'get_client_performance',
    'get_campaign_summary', 'get_campaign_performance',
    'get_adset_summary', 'get_adset_performance',
    'get_ad_summary', 'get_ad_performance', 'get_breakdowns',
    'get_creative_details', 'get_alerts', 'get_learnings',
    'query_meta_insights', 'query_meta_creatives',
    'search_methodology_safe',
    'reply_in_thread',
  ],
  production_manager: [
    'recall', 'remember', 'search_memories',
    'list_clients',
    'query_aot_tasks', 'query_aot_adsets', 'count_aot_tasks', 'count_aot_adsets', 'check_ads_in_meta', 'search_notion',
    'inspect_piper_actions',
    'remember_cadence_target', 'get_cadence_targets', 'inspect_data_quality',
    'get_cadence_read', 'get_cadence_read_all',
    'search_meetings', 'get_meeting_summary', 'get_meeting_transcript', 'list_recent_meetings',
    'search_slack_messages', 'read_slack_channel',
    'update_aot_task_status',
    'post_message', 'reply_in_thread',
  ],
} as const;

export type ToolProfile = keyof typeof toolProfiles;

export type ToolName = (typeof toolProfiles)[ToolProfile][number];
