-- briefings: scheduled and on-demand briefings generated by Jasmin
CREATE TABLE briefings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL CHECK (type IN ('morning', 'eod', 'on_demand')),
  briefing_text TEXT NOT NULL,
  data_sources_used INTEGER NOT NULL DEFAULT 0,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_briefings_generated ON briefings(generated_at DESC);
CREATE INDEX idx_briefings_type ON briefings(type);
