-- Weekly client reports generated by Ada
CREATE TABLE IF NOT EXISTS client_reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  client_code TEXT NOT NULL,
  report_week DATE NOT NULL,
  report_text TEXT NOT NULL,
  condensed_data JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'approved', 'edited', 'skipped', 'sent')),
  approved_at TIMESTAMPTZ,
  slack_ts TEXT,
  slack_channel TEXT,
  input_tokens INTEGER,
  output_tokens INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_client_reports_week
  ON client_reports(client_code, report_week);
